require:
  - rubocop-rspec
  - rubocop-rake

AllCops:
  NewCops: enable

Layout/ArgumentAlignment:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/HeredocArgumentClosingParenthesis:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Naming/InclusiveLanguage:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

Style/Documentation:
  Enabled: false
